### ISSUE TITLE
Exclude field

### ISSUE THREAD

**Issue by Odselmaa** [closeio/flask-mongorest#112]
How to exclude one or more fields? 
Because I have so many fields and need to exclude one field

**Comment by bitrot-sh** [comment]
While defining your Resource based class, include the fields that you want to return.
Example:
```
class UserResource(Resource):
    document = User
    filters = {
        'email': [Exact, IExact, Contains, IContains],
        'username': [Exact, IExact, Contains, IContains],
    }
    fields = ['username']
```

The above example will only return the field username (excluding email).

**Comment by sunitsingh1** [comment]
How to modified field value at the time of post request (i want to change the value of request data fields) in Resource() class

**Comment by AlecRosenbaum** [comment]
I think you should be able to do something like this:

```python
class UserResource(Resource):
    document = User
    fields = ['username', 'upper_username']

	def upper_username(self, obj):
		return obj.username.upper()
```

**Comment by sunitsingh1** [comment]
No this one return only not saving in db.
I want to change the value of field and then store in db
At a time of post request.

**Comment by AlecRosenbaum** [comment]
try overriding: 
```python
	def create_object(self, **kwargs):
		# custom stuff
		custom_val = self.raw_data.pop('custom_val')

		super().create_object(**kwargs)
```

**Comment by sunitsingh1** [comment]
Basically i get the base64 data from request and i want to convert it in
jpg and store in local system and it's path store in db .
If you have any sample of code for this situation using flask_mongorest.
Plz share

**Comment by AlecRosenbaum** [comment]
I do not have sample code for that scenario.

**Comment by sunitsingh1** [comment]
Ok I will try.
Thank you

**Comment by sunitsingh1** [comment]
I tried it's work but it not returning anything . How to return like
earlier
Plz help if any idea
