### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ddorian** [closeio/flask-mongorest#47]
It's been nearly a year?

**Comment by thomasst** [comment]
We're currently working on cleaning flask-mongorest up in the `cleanup` branch. The branch has been mostly stable so feel free to give it a try if you want to try the latest version:
https://github.com/elasticsales/flask-mongorest/pull/62

Unfortunately we're not using Python 3 in production so we're not ready for Python 3 at this point.

**Comment by thomasst** [comment]
Just released 0.2 on PyPi (https://pypi.python.org/pypi/Flask-MongoRest)
