### ISSUE TITLE
POST redirect when url without slash (/) at the end

### ISSUE THREAD

**Issue by guti576** [closeio/flask-mongorest#67]
When I send a POST request to an url without ended in slash (f.e /user), it redirects me to the same url ended with the slash (/user/) but with a GET  instead of a POST method.

Could you please give me a solution for this issue?

Thanks.

**Comment by wojcikstefan** [comment]
Hi @guti576, we could technically implement an HTTP 307 redirect, but it's pretty uncommon. Why can't you simply only use URLs with a trailing slash?

**Comment by guti576** [comment]
Thanks for answering. That is the solution I have adopted, but the initial idea was to work with and without slash.

**Comment by guti576** [comment]
@wojcikstefan you can solve this issue just adding :

```python
app.url_map.strict_slashes = False
```
