### ISSUE TITLE
how to paginate

### ISSUE THREAD

**Issue by houkk** [closeio/flask-mongorest#70]

**Comment by wojcikstefan** [comment]
`_limit` and `_skip` parameters can be used to paginate through the results. For example, the first three pages for a "blog post" resource (100 records per page) are given below:

* Page 1: `/api/v1/blogpost/?_skip=0&_limit=100`
* Page 2: `/api/v1/blogpost/?_skip=100&_limit=100`
* Page 3: `/api/v1/blogpost/?_skip=200&_limit=100`
