### ISSUE TITLE
Python 3 incompatible syntax on views.py

### ISSUE THREAD

**Issue by marco-lavagnino** [closeio/flask-mongorest#86]
There are a couple of `except Exception, e:` in views.py and that syntax is incompatible with python 3. A simple change to  `except Exception as e:` should solve the issue.

**Comment by wojcikstefan** [comment]
Thanks Marco, `except Exception as e` sounds good. Care to send a PR?

**Comment by marco-lavagnino** [comment]
ok, sending it soon :)

2016-07-19 19:33 GMT-03:00 Stefan Wójcik <notifications@github.com>:

**Comment by marco-lavagnino** [comment]
Seems like there are many bits of the library incompatible with python 3, and changing the syntax of the exception catching wouldn't be enough.

**Comment by thomasst** [comment]
Thanks for reporting these! I'm closing this in favor of https://github.com/closeio/flask-mongorest/pull/99
