### ISSUE TITLE
Compatibility with mongoengine[original]

### ISSUE THREAD

**Issue by michaelbukachi** [closeio/flask-mongorest#93]
Hello I've forked the project and I'm trying to update the syntax and dependencies to support the latest versions of python. I'm kinda stuck at mongoengine since a forked version is being used. Is there any way i could get the differences between the two or do i have to stick to the forked version.

**Comment by thomasst** [comment]
Support for Python 3 / official MongoEngine is in progress here: https://github.com/closeio/flask-mongorest/pull/99

**Comment by thomasst** [comment]
Using official MongoEngine with flask-mongorest should work now. If you have any specific issues with the latest version, feel free to open a specific issue.
